name: fancy_switch_flutter
description: "A custom animated switch with smooth transitions and themed backgrounds, ideal for toggling between day and night modes."

version: 0.0.5
homepage: https://github.com/shahparan71/flutter_fancy_image_switch
repository: https://github.com/shahparan71/flutter_fancy_image_switch
issue_tracker: https://github.com/shahparan71/flutter_fancy_image_switch/issues
topics:
  - switch
  - animated
  - custom-widget
  - flutter

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
